import json
import asyncio
from src.shared_services.docker_sandbox import execute_in_container

async def run_zap_dast(container, target_dir: str, job_id: str, db_client, target_url: str):
    """
    Runs OWASP ZAP (Feature 5) inside the provisioned ephemeral container.
    """
    scanner_type = 'owasp_zap'
    
    try:
        # Create initial scanner run record
        db_client.table("scanner_runs").insert({
            "scan_job_id": job_id,
            "scanner_type": scanner_type,
            "status": "running",
            "raw_output": {}
        }).execute()
    except Exception as e:
        print(f"[LiveURL Job {job_id}] Failed to init ZAP scanner run in DB: {e}")
        return
        
    zap_cmd = f"/usr/local/bin/zap.sh -cmd -quickurl {target_url} -quickout {target_dir}/zap_report.json -quickprogress -config scanner.delayInMs=100"
    
    try:
        print(f"[LiveURL Job {job_id}] Invoking ZAP active scan against {target_url} (Max 30 min)...")
        # 30-minute timeout for DAST Active Scan (1800 seconds)
        exit_code, output = await execute_in_container(container, zap_cmd, timeout_seconds=1800)
    except TimeoutError:
        print(f"[LiveURL Job {job_id}] ZAP execution timed out after 30 minutes.")
        db_client.table("scanner_runs").update({
            "status": "failed",
            "raw_output": {"error": "ZAP active scan timed out (1800s limit)."}
        }).eq("scan_job_id", job_id).eq("scanner_type", scanner_type).execute()
        return
    except Exception as e:
        print(f"[LiveURL Job {job_id}] Error running ZAP: {e}")
        db_client.table("scanner_runs").update({
            "status": "failed",
            "raw_output": {"error": str(e)}
        }).eq("scan_job_id", job_id).eq("scanner_type", scanner_type).execute()
        return

    # Check for report file
    try:
        exit_code, out_bytes = await execute_in_container(container, f"cat {target_dir}/zap_report.json")
        if exit_code == 0:
            parsed_json = json.loads(out_bytes.decode('utf-8'))
            db_client.table("scanner_runs").update({
                "status": "completed",
                "raw_output": parsed_json
            }).eq("scan_job_id", job_id).eq("scanner_type", scanner_type).execute()
            print(f"[LiveURL Job {job_id}] ZAP scan completed and recorded.")
        else:
            print(f"[LiveURL Job {job_id}] ZAP generated no report file (exit code {exit_code}).")
            db_client.table("scanner_runs").update({
                "status": "failed",
                "raw_output": {"error": "No JSON report generated by ZAP."}
            }).eq("scan_job_id", job_id).eq("scanner_type", scanner_type).execute()
    except Exception as e:
         print(f"[LiveURL Job {job_id}] Error parsing ZAP report: {e}")
         db_client.table("scanner_runs").update({
             "status": "failed",
             "raw_output": {"error": f"Report parsing failed: {e}"}
         }).eq("scan_job_id", job_id).eq("scanner_type", scanner_type).execute()
